spring:
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    #database-platform:

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root123
    url: jdbc:mariadb://localhost:3306/bootex


logging:
  level:
    org.springframework.security: DEBUG
